### PR TITLE
Add cloudwatch logging options for runCommand patch manager tasks

### PR DESCRIPTION
**Pull request by gpapakyriakopoulos**
Based on AWS documentation [1] runCommand executions support directly logging to cloudwatch instead of an S3 bucket.

To that end we introduce 3 extra module variables, the first 2 (`cloudwatch_log_output_enabled` & `cloudwatch_log_group_name`) to configure whether cloudwatch logging is enabled and whether a custom cloudwatch log group name should be provided (if not a default is created, see [2]). The 3rd variable (`s3_log_output_enabled`) is introduced to optionally disable supplying an S3 bucket for logging, since cloudwatch logging should be enough for some use cases.

[1] https://docs.aws.amazon.com/systems-manager/latest/userguide/sysman-rc-setting-up-cwlogs.html
[2] https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ssm_maintenance_window_task#cloudwatch_log_group_name

### CODE REVIEW

**Comment by gpapakyriakopoulos** [comment]
I was not able to update the readme as the `make` command failed for me on MacOS. If you would be so kind as to generate the README files correctly yourselves and update the PR I would appreciate it

**Comment by gberenice** [comment]
> I was not able to update the readme as the `make` command failed for me on MacOS. If you would be so kind as to generate the README files correctly yourselves and update the PR I would appreciate it

@gpapakyriakopoulos thanks for your contribution! The issue with README generation will be fixed today, I'll re-run tests when it's done.

**Comment by gberenice** [comment]
@gpapakyriakopoulos could you please run again the following commands locally?
```
  make init
  make readme
```
I believe this should work now 👍

**Comment by gpapakyriakopoulos** [comment]
> @gpapakyriakopoulos could you please run again the following commands locally?
> 
> ```
>   make init
>   make readme
> ```
> 
> I believe this should work now 👍

Seemed to worked correctly this time! I've added the README update in the PR, thanks!

**Review by gberenice — DISMISSED** [review]
LGTM :shipit:

**Comment by gberenice** [comment]
@gpapakyriakopoulos mind syncing your fork with the base branch?

**Comment by gpapakyriakopoulos** [comment]
Just rebased using the GitHub button @gberenice. Seems like you need to run terratest again + add your review again.

**Review by gberenice — APPROVED** [review]

**Comment by gberenice** [comment]
A new version [v1.0.1](https://github.com/cloudposse/terraform-aws-ssm-patch-manager/releases/tag/1.0.1) was released. Thanks @gpapakyriakopoulos !

**Pull request merged**
