### PR TITLE
Upgrade to support AWS provider v4

### PR DESCRIPTION
**Pull request by woz5999**
## what
* Upgrade to support AWS provider v4
* Upgrade to latest s3 bucket module

## why
* This module is currently unusable in projects using AWS provider v4

## references
* closes https://github.com/cloudposse/terraform-aws-ssm-patch-manager/pull/3

### CODE REVIEW

**Review by korenyoni — DISMISSED** [review]
Tests are failing — has to do with the Terraform version constraint in `examples/complete` https://github.com/cloudposse/actions/runs/5570481170?check_suite_focus=true

**Review by nitrocode — APPROVED** [review]

**Pull request merged**
